//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int MoveX = 0;
    public const int MoveY = 1;
    public const int Jump = 2;
    public const int Primary = 3;
    public const int Secondary = 4;
    public const int Previous = 5;
    public const int Next = 6;
    public const int MenuX = 7;
    public const int MenuY = 8;
    public const int MenuAccept = 9;
    public const int MenuCancel = 10;
    public const int _count = 11;
}
